# version: "3.7"
services:
  app:
    build:
      context: .
    container_name: react_front
    restart: always
    volumes:
      - "./public:/app/public"
      - "./src:/app/src"
    command: npm start

    ports:
      - 3000:3000

    environment:
      - NODE_ENV=development
